[Settings]
gtk-application-prefer-dark-theme=true
gtk-font-name=Roboto 11
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=Adwaita
gtk-fallback-icon-theme=Adwaita
gtk-cursor-theme-name=catppuccin-macchiato-dark-cursors
gtk-cursor-theme-size=24

# vim:commentstring=#%s
