---
gtk_config:
  path: wm/gtk
  links:
    - src: settings.ini
      dest: "{{ gtk_3_dir }}/"
    - src: settings.ini
      dest: "{{ gtk_4_dir }}/"
    - src: gtk-environment.conf
      dest: "{{ environment_d_dir }}/"
  pacman_packages:
    - xdg-desktop-portal-gtk

gtk_themes_dir: "~/.themes"
gtk_3_dir: "{{ xdg_config_home }}/gtk-3.0"
gtk_4_dir: "{{ xdg_config_home }}/gtk-4.0"
environment_d_dir: "{{ xdg_config_home }}/environment.d"
