---
java_config:
  path: lang/java
  brew_formulae:
    - maven
    - gradle
    - java
  brew_casks:
    - adoptopenjdk/openjdk/adoptopenjdk11
  brew_taps:
    - adoptopenjdk/openjdk
  pacman_packages:
    - jdk-openjdk
    - jre-openjdk
    - jdk11-openjdk
    - jre11-openjdk
    - maven
    - gradle
