---
java_config:
  path: lang/java
  brew_formulas:
    - maven
    - gradle
    - java
  brew_casks:
    - temurin8
    - adoptopenjdk/openjdk/adoptopenjdk11
  brew_taps:
    - homebrew/cask-versions
    - adoptopenjdk/openjdk
  pacman_packages:
    - jdk-openjdk
    - jre-openjdk
    - jdk11-openjdk
    - jre11-openjdk
    - jdk8-openjdk
    - jre8-openjdk
    - maven
    - gradle
