espanso_config:
  path: keyboard/espanso
  brew_casks:
    - espanso
  aur_packages:
    - espanso-wayland
  links:
    - match
    - config
    - src: imports_macos.yml
      dest: "{{ dotfiles }}/keyboard/espanso/match/os_imports.yml"
      rename: imports.yml
      condition: "{{ is_macos }}"
    - src: imports_arch.yml
      dest: "{{ dotfiles }}/keyboard/espanso/match/os_imports.yml"
      rename: imports.yml
      condition: "{{ is_arch }}"
    - src: espanso-override.conf
      dest: "{{ espanso_systemd_override_dir }}/"
      rename: override.conf
      condition: "{{ is_arch }}"

espanso_systemd_override_dir: "{{ xdg_config_home }}/systemd/user/espanso.service.d"
