require('packer_init')
require('core/options')
require('core/keymaps')
require('core/autocommands')
require('core/colors')
require('plugins/telescope')
require('plugins/nvim-tree')
require('legacy/navigation')
