---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulae:
    - neovim
    - fzf
    - bat
    - python
    - pylint
    - black
    - glow
    - stylua
    - pgformatter
    - taplo
    - tree-sitter-cli
  pacman_packages:
    - neovim
    - fzf
    - bat
    - python
    - python-pylint
    - python-black
    - stylua
    - pgformatter
    - tree-sitter-cli
  npm_packages:
    - kulala-ls
    - kulala-fmt
    - eslint_d
  aur_packages:
    - glow-bin
  links:
    - init.lua
    - lua
    - after
    - src: scratch.desktop
      dest: "{{ xdg_applications_dir }}/"
      condition: "{{ is_arch }}"
    - src: obsidian-popup.desktop
      dest: "{{ xdg_applications_dir }}/"
      condition: "{{ is_arch }}"
