---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
    - fzf
    - bat
    - python
    - pylint
    - black
    - glow
    - stylua
    - pgformatter
  pacman_packages:
    - neovim
    - fzf
    - bat
    - python
    - python-pylint
    - python-black
  npm_packages:
    - kulala-ls
    - kulala-fmt
  aur_packages:
    - glow-bin
  links:
    - init.lua
    - lua
    - after
