---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
    - fzf
    - bat
    - python
    - pylint
    - black
    - glow
    - stylua
  pacman_packages:
    - neovim
    - fzf
    - bat
    - python
    - python-pylint
    - python-black
  aur_packages:
    - glow-bin
  npm_packages:
    - bash-language-server
    - diagnostic-languageserver
    - typescript
    - typescript-language-server
    - vscode-langservers-extracted
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - pyright
    - '@tailwindcss/language-server'
    - '@prisma/language-server'
    - graphql-language-service-cli
  pip_packages:
    - pynvim
  links:
    - init.lua
    - lua
    - after
