---
neovim_config:
  path: editor/neovim
  dirname: nvim
  brew_formulas:
    - neovim
    - fzf
    - bat
    - python
    - pylint
    - black
    - glow
  pacman_packages:
    - neovim
    - fzf
    - bat
    - python
    - python-pylint
    - python-black
  aur_packages:
    - lua-format
    - glow-bin
  npm_packages:
    - bash-language-server
    - diagnostic-languageserver
    - typescript
    - typescript-language-server
    - vscode-langservers-extracted
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - pyright
    - '@tailwindcss/language-server'
    - '@prisma/language-server'
    - graphql-language-service-cli
  pip_packages:
    - pynvim
  links:
    - init.lua
    - lua
  # links:
  #   - init.vim
  #   - plugins.vim
  #   - general.vim
  #   - autocmds.vim
  #   - theme.vim
  #   - keybindings.vim
  #   - experimental.vim
  #   - plugins.d
  #   - lua
  #   - UltiSnips
