#! /bin/sh

_is_callable () {
  command -v "$1" >/dev/null || return 1
}

if ! _is_callable sxhkd ; then
  echo "sxhkd not found : exiting"
  bspc quit
  exit 1
fi

# Defaults: look them up!

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DVI-D-0 -d I II III IV V
bspc monitor DVI-I-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#89ddff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a tmux_alacritty desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

_run_if_present () {
  case $1 in
    "/"*) script="$1" ;;
    *) script="${HOME}/.config/$1" ;;
  esac
  [ -x "$script" ] && "$script"
}

_run_if_present feh/set-background.sh
_run_if_present polybar/launch.sh
_run_if_present picom/launch.sh
_run_if_present dunst/launch.sh

_run_if_present xkb/setup-keybindings.sh
_run_if_present arch/xinput.sh
_run_if_present sxhkd/launch.sh
