#! /bin/sh

_is_callable () {
  command -v "$1" >/dev/null || return 1
}

if ! _is_callable sxhkd ; then
  echo "sxhkd not found : exiting"
  bspc quit
  exit 1
fi

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DVI-I-1 -d 1
bspc monitor DP-1 -d 2 3 4 5 6
bspc monitor DVI-D-0 -d 7 8 9 10

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#89ddff"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs desktop='^4' state=fullscreen follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a TmuxAlacritty desktop='^5' follow=on

# Rules don't work for electron apps - see:
# https://github.com/baskerville/bspwm/issues/291#issuecomment-145329416
bspc rule -a spotify desktop='^7'
bspc rule -a Discord desktop='^8' follow=on state=fullscreen
# Check wm/bspwm/launch_on_desktop.sh for a workaround

_run_if_present () {
  case $1 in
    "/"*) script="$1" ;;
    *) script="${HOME}/.config/$1" ;;
  esac
  [ -x "$script" ] && "$script"
}

_run_if_present feh/set-background.sh
_run_if_present polybar/launch.sh
_run_if_present picom/launch.sh
_run_if_present dunst/launch.sh

_run_if_present xkb/setup-keybindings.sh
_run_if_present arch/xinput.sh
_run_if_present sxhkd/launch.sh

_run_if_present arch/autostart.sh
