#! /bin/sh

_is_callable () {
  command -v "$1" >/dev/null || return 1
}

if ! _is_callable sxhkd ; then
  echo "sxhkd not found : exiting"
  bspc quit
  exit 1
fi

xrandr --output DP-1 --auto --primary --output DVI-D-0 --auto --right-of DP-1 --output DVI-I-1 --auto --left-of DP-1

bspc monitor DVI-I-1 -d A1 A2 A3 A4 A5
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DVI-D-0 -d B1 B2 B3 B4 B5

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#ffcb6b"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a TmuxAlacritty desktop='1' follow=on
bspc rule -a Google-chrome desktop='2'
bspc rule -a jetbrains-idea-ce desktop='3' follow=on
bspc rule -a Emacs desktop='4' state=fullscreen follow=on

bspc rule -a firefox desktop='A5'

bspc rule -a Slack desktop='B1' follow=on
# bspc rule -a spotify desktop='B2' (*)
# bspc rule -a Discord desktop='B3' follow=on state=fullscreen (*)
bspc rule -a 1Password desktop='B5' follow=on

bspc rule -a VpnSession state=floating
bspc rule -a NotesAlacritty state=floating center=true rectangle=1600x1000+0+0

# (*)
# Rules don't work for electron apps - see:
# https://github.com/baskerville/bspwm/issues/291#issuecomment-145329416
# Check wm/bspwm/launch_on_desktop.sh for a workaround

_run_if_present() {
  case $1 in
    "/"*) script="$1" ;;
    *) script="${HOME}/.config/$1" ;;
  esac
  [ -x "$script" ] && shift && "$script" "$@"
}

_run_if_present feh/set-background.sh ~/.wallpaper
_run_if_present polybar/launch.sh
_run_if_present picom/launch.sh
_run_if_present dunst/launch.sh

_run_if_present xkb/setup-keybindings.sh
_run_if_present arch/xinput.sh
_run_if_present sxhkd/launch.sh

_run_if_present arch/autostart.sh
