---
tmux_config:
  path: shell/tmux
  brew_formulae:
    - tmux
  pacman_packages:
    - tmux
  links:
    - tmux.conf
    - tmux.remote.conf
    - tmux.theme.conf
    - scripts
    - extensions
    - src: tmux_switch_session.sh
      dest: "{{ xdg_bin_home }}/"
      rename: tmux_switch_session
    - src: navigate-macos.sh
      dest: "{{ xdg_bin_home }}/"
      rename: navigate
      condition: "{{ is_macos }}"
    - src: bash_repl.sh
      dest: "{{ xdg_bin_home }}/"
      rename: bash_repl
    - src: jq_repl.sh
      dest: "{{ xdg_bin_home }}/"
      rename: jq_repl
    - src: tmux_warning_wrapper.sh
      dest: "{{ xdg_bin_home }}/"
      rename: tmux_warning_wrapper
    - src: tmux_active_pane_directory.sh
      dest: "{{ xdg_bin_home }}/"
      rename: tmux_active_pane_directory
    - src: create_popup_session.sh
      dest: "{{ xdg_bin_home }}/"
      rename: create_popup_session
    - src: display_stateful_popup.sh
      dest: "{{ xdg_bin_home }}/"
      rename: display_stateful_popup
    - src: toggle_stateful_popup.sh
      dest: "{{ xdg_bin_home }}/"
      rename: toggle_stateful_popup
