---
tmux_config:
  path: shell/tmux
  brew_formulas:
    - tmux
  pacman_packages:
    - tmux
  links:
    - tmux.conf
    - tmux.remote.conf
    - tmux.theme.conf
    - scripts
    - src: tmux_switch_session.sh
      dest: "{{ xdg_bin_home }}/"
      rename: tmux_switch_session
    - src: navigate-macos.sh
      dest: "{{ xdg_bin_home }}/"
      rename: navigate
      condition: "{{ is_macos }}"
    - src: bash_repl.sh
      dest: "{{ xdg_bin_home }}/"
      rename: bash_repl
