---
topics:
  dotfiles:
    - name: cli
      state: present
      config: "{{ cli_config }}"
  projects:
    - name: notes
      state: present
      config: "{{ notes_config }}"
  tools:
    - name: slides
      state: present
      config: "{{ slides_config }}"
  base:
    - name: macos
      state: present
      config: "{{ macos_config }}"
    - name: work
      state: present
      config: "{{ work_config }}"
    - name: task
      state: present
      config: "{{ task_config }}"
  editor:
    - name: vim
      state: disabled
      config: "{{ vim_config }}"
    - name: neovim
      state: present
      config: "{{ neovim_config }}"
    - name: emacs
      state: present
      config: "{{ emacs_config }}"
    - name: editorconfig
      state: present
      config: "{{ editorconfig_config }}"
    - name: vscode
      state: present
      config: "{{ vscode_config }}"
    - name: intellij
      state: absent
      config: "{{ intellij_config }}"
  keyboard:
    - name: fasterkeys
      state: present
      config: "{{ fasterkeys_config }}"
    - name: hammerspoon
      state: present
      config: "{{ hammerspoon_config }}"
    - name: karabiner
      state: present
      config: "{{ karabiner_config }}"
  terminal:
    - name: alacritty
      state: present
      config: "{{ alacritty_config }}"
  shell:
    - name: bash
      state: present
      config: "{{ bash_config }}"
    - name: git
      state: present
      config: "{{ git_config }}"
    - name: ssh
      state: present
      config: "{{ ssh_config }}"
    - name: tmux
      state: present
      config: "{{ tmux_config }}"
    - name: zsh
      state: present
      config: "{{ zsh_config }}"
  dev:
    - name: ansible
      state: present
      config: "{{ ansible_config }}"
    - name: cicd
      state: present
      config: "{{ cicd_config }}"
    - name: docker
      state: present
      config: "{{ docker_config }}"
    - name: gcloud
      state: present
      config: "{{ gcloud_config }}"
    - name: vagrant
      state: absent
      config: "{{ vagrant_config }}"
    - name: kubernetes
      state: present
      config: "{{ kubernetes_config }}"
    - name: kafka
      state: absent
      config: "{{ kafka_config }}"
    - name: web
      state: present
      config: "{{ web_config }}"
  lang:
    - name: dart
      state: absent
      config: "{{ dart_config }}"
    - name: dotnet
      state: absent
      config: "{{ dotnet_config }}"
    - name: go
      state: absent
      config: "{{ go_config }}"
    - name: java
      state: present
      config: "{{ java_config }}"
    - name: node
      state: present
      config: "{{ node_config }}"
    - name: python
      state: present
      config: "{{ python_config }}"
    - name: ruby
      state: present
      config: "{{ ruby_config }}"
    - name: rust
      state: present
      config: "{{ rust_config }}"
