enable_selector = true
selector = "handlr-selector"

# Work domains - auto-route to work browser
[[handlers]]
exec = "chrome-work %U"
terminal = false
regexes = ['https?://github\.com/bemlo(/.*)?','https?://app\.bemlo\.com(/.*)?']

[[handlers]]
exec = "chrome-personal %U"
terminal = false
regexes = ['https?://github\.com/eliasnorrby(/.*)?']
