bind = SUPER, RETURN, exec, $terminal

bind = $hyper, T, exec, focus_or_run TmuxKitty tmux_kitty
bind = $hyper, C, exec, launch_on_workspace 2 google-chrome chrome_personal
bind = $hyper, W, exec, launch_on_workspace 3 google-chrome chrome_work
bind = $hyper, A, exec, focus_or_run chromium
bind = $hyper, U, exec, focus_or_run spotify
# vim: ft=hyprlang
