bind = SUPER, RETURN, exec, $terminal

bind = $hyper, T, exec, focus_or_run TmuxKitty tmux_kitty
bind = $hyper, C, exec, launch_on_workspace 2 google-chrome chrome_personal
bind = $hyper, W, exec, launch_on_workspace 3 google-chrome chrome_work
bind = $hyper, A, exec, focus_or_run chromium
bind = $hyper, U, exec, focus_or_run spotify

# tmux window select
bind = $hyper, 1, exec, tmux select-window -t 1
bind = $hyper, 2, exec, tmux select-window -t 2
bind = $hyper, 3, exec, tmux select-window -t 3
bind = $hyper, 4, exec, tmux select-window -t 4
bind = $hyper, 5, exec, tmux select-window -t 5
bind = $hyper, 6, exec, tmux select-window -t 6
bind = $hyper, 7, exec, tmux select-window -t 7
bind = $hyper, 8, exec, tmux select-window -t 8
bind = $hyper, 9, exec, tmux select-window -t 9

# vim: ft=hyprlang
