exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprlauncher -d
exec-once = waybar

exec-once = hyprpolkitagent

exec-once = dropbox

exec-once = ~/.local/bin/tmux_set_env

exec-once = ~/.dotfiles/wm/gtk/gsettings.sh

# vim: ft=hyprlang
