exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

# TODO: Add dropbox et al

# vim: ft=hyprlang
