exec-once = hyprpaper
exec-once = hypridle

exec-once = hyprpolkitagent

exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'catppuccin-mocha-dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

# TODO: Add dropbox et al

# vim: ft=hyprlang
