# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,se
    kb_variant =
    kb_model =
    kb_options = altwin:swap_lalt_lwin
    kb_rules =
    repeat_rate = 75
    repeat_delay = 400

    natural_scroll = true

    follow_mouse = 1
    special_fallthrough = false

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

# Force ydotool to use US layout (it always sends US keycodes)
device {
    name = ydotoold-virtual-device
    kb_layout = us
    kb_variant =
    kb_options =
}

# vim: ft=hyprlang
