# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = opacity 0.9 0.9, class:^(kitty)$
windowrule = opacity 0.9 0.9, class:^(TmuxKitty)$
windowrule = opacity 0.9 0.9, class:^(obsidian)$
windowrule = opacity 0.9 0.9, class:^(BtopKitty)$

windowrulev2 = focusonactivate, class:^(google-chrome)$

# vim: ft=hyprlang
