# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = match:class kitty, match:title kitty, float

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

windowrule = match:class lxqt-openssh-askpass, float on

windowrule = match:class ChromePersonal, focus_on_activate on
windowrule = match:class ChromeWork, focus_on_activate on

windowrule {
  name = "Goole Meet Picture-in-Picture"
  match:title = Meet - .*

  float = on
  pin = on
  size = 400 300
  move = (monitor_w-430) (monitor_h-330)
}

windowrule {
  name = "Flameshot Screenshot Tool"
  match:class = flameshot

  rounding = 0
  float = on
  pin = on
  animation = fade
  move = 0 0
}

# vim: ft=hyprlang
