---
task_config:
  path: base/task
  links:
    - taskrc
    - src: task_alacritty.sh
      dest: "{{ xdg_bin_home }}/"
      rename: task_alacritty
    - src: taskwarrior-tui.desktop
      dest: "{{ xdg_applications_dir }}/"
      condition: "{{ is_arch }}"
    - src: task_module.sh
      dest: "{{ xdg_bin_home }}/"
      rename: task_module
    - src: script/gh_pr_task_sync.sh
      dest: "{{ xdg_bin_home }}/"
      rename: gh_pr_task_sync
    - src: script/task_open_pr.sh
      dest: "{{ xdg_bin_home }}/"
      rename: task_open_pr
    - src: script/add_wait_tag.sh
      dest: "{{ xdg_bin_home }}/"
      rename: add_wait_tag
  brew_formulae:
    - task
    - taskwarrior-tui
  brew_casks:
    - omnifocus
    - todoist
  mas_apps:
    - id: 904280696
      name: "Things"
  pacman_packages:
    - task
    - taskwarrior-tui
