---
cicd_config:
  path: dev/cicd
  brew_formulae:
    - tfenv
    - terraform-ls
    - tflint
  brew_casks:
    - ngrok
  pacman_packages:
    - terraform
  aur_packages:
    - tfenv
    - terraform-ls-bin
    - tflint-bin
