---
cicd_config:
  path: dev/cicd
  brew_taps:
    - buildpacks/tap
  brew_formulas:
    - tektoncd-cli
    - terraform
    - terraform-ls
    - tflint
    - pack
    - argocd
  brew_casks:
    - ngrok
  pacman_packages:
    - tekton-cli
    - terraform
    - argocd
  npm_packages:
    - semantic-release-cli
  aur_packages:
    - pack-cli-bin
    - terraform-ls-bin
    - tflint-bin
