---
web_config:
  path: dev/web
  brew_formulae:
    - stripe
  brew_taps:
    - stripe/stripe-cli
  brew_casks:
    - insomnia
  npm_packages:
    - lorem-ipsum
    - prettier
    - oxfmt
    - serve
