font_size        12

font_family      family='VictorMono Nerd Font' postscript_name=VictorMonoNF-Regular
bold_font        family='VictorMono Nerd Font' style=Bold
italic_font      auto
bold_italic_font family='VictorMono Nerd Font' style='Bold Italic'

window_margin_width 3
