# font_family      VictorMono Nerd Font Mono
font_family      Victor Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
text_composition_strategy 1.0 0

background_opacity 0.90
background_blur 30
hide_window_decorations titlebar-only
window_margin_width 10
macos_option_as_alt yes
