---
# defaults file for ansible-role-dotfiles
dotfiles_repo: https://github.com/eliasnorrby/dotfiles

xdg_config_home: "~/.config"
xdg_cache_home: "~/.cache"
xdg_data_home: "~/.local/share"
xdg_bin_home: "~/.local/bin"

dotfiles: "~/.dotfiles"
dotfiles_version: "develop"
dotfiles_data: "{{ xdg_data_home }}/dotfiles"

is_interactive: false

topics:
  editor:
    - name: neovim
      state: present
      config:
        path: editor/neovim
        brew_formulas:
          - neovim
        links:
          - init.lua
  shell:
    - name: zsh
      state: present
      config:
        path: shell/zsh
        brew_formulas:
          - zsh
          - fzf
          - ripgrep
        links:
          - zshrc
          - src: zshenv
            dest: ~/.zshenv
    - name: git
      state: present
      config:
        path: shell/git
