---
node_config:
  path: lang/node
  links:
    - src: select_and_run_package_script.sh
      dest: "{{ xdg_bin_home }}/"
      rename: select_and_run_package_script
  brew_formulas:
    - node
    - yarn
    - fnm
    - pnpm
  pacman_packages:
    - nodejs
    - npm
    - yarn
  aur_packages:
    - fnm-bin

npm_global_packages_dir: "{{ xdg_cache_home }}/npm-global"
