---
- name: create dir for global packages
  file:
    state: directory
    path: "{{ npm_global_packages_dir }}/lib"

- name: add yarn completion
  when: is_macos
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_yarn
    dest: "{{ zsh_custom_completion_dir }}/_yarn"
