---
claude_config:
  path: ai/claude
  brew_casks:
    - claude
    - claude-code
  links:
    - src: claude_editor.sh
      dest: "{{ xdg_bin_home }}/"
      rename: claude_editor
    - src: claude_persisted_editor.sh
      dest: "{{ xdg_bin_home }}/"
      rename: claude_persisted_editor
    - src: claude_notification.sh
      dest: "{{ xdg_bin_home }}/"
      rename: claude_notification
    - src: settings.json
      dest: "{{ claude_home }}/"
    - src: statusline.sh
      dest: "{{ claude_home }}/"
    - src: home-claude.md
      dest: ~/
      rename: CLAUDE.md

claude_home: "~/.claude"
