---
vim_config:
  path: editor/vim
  brew_formulas:
    - vim
  links:
    - .vimrc
    # - src: .only-src
    # - just-list-item
    # - src: a-file
    #   dest: a-directory/
    # - src: a-file
    #   dest: an-actual-file
