---
font_config:
  path: base/font
  brew_casks:
    - font-victor-mono
    - font-symbols-only-nerd-font
    - font-hack-nerd-font
    - font-iosevka-nerd-font
    - font-mononoki-nerd-font
    - font-victor-mono-nerd-font
  pacman_packages:
    - ttf-font-awesome
    - ttf-iosevka-nerd
  aur_packages:
    - nerd-fonts-hack
    - nerd-fonts-mononoki
    - nerd-fonts-victor-mono
    - ttf-devicons
    - ttf-mononoki
    - ttf-material-design-icons-webfont
