---
emacs_config:
  path: editor/emacs
  links:
    - src: doom
      dest: "{{ xdg_config_home }}/"
  brew_taps:
    - d12frosted/emacs-plus
  brew_formulas:
    - name: emacs-plus
      install_options: without-spacemacs-icon
