alias g="git"
alias git="nocorrect git"

alias gcr="git reset --soft HEAD^"

alias ga="git add"
alias gaa="git add -A"
alias gc="git commit -v"
alias gcd="git checkout develop"
alias gcm="git checkout master"
alias gco="git checkout"
alias gd="git diff"
alias glog="git log --oneline --decorate --graph"
alias glogb="glog --branches"
alias gp="git push"
alias gl="git pull"
alias glnr="git pull --no-rebase"
alias gst="git status"
alias grv="git remote -v"
