---
git_config:
  path: shell/git
  links:
    - config
    - attributes
    - aliases
    - config-irori
    - config-bemlo
    - config-notes
    - ignore
    - src: gh-config.yml
      dest: "{{ xdg_config_home }}/gh/"
      rename: config.yml
    - src: gh_browse.sh
      dest: "{{ xdg_bin_home }}/"
      rename: gh_browse
    - src: list_branch_files.sh
      dest: "{{ xdg_bin_home }}/"
      rename: list_branch_files
    - src: watch_branches.sh
      dest: "{{ xdg_bin_home }}/"
      rename: watch_branches
  brew_formulas:
    - git
    - tig
    - hub
    - gh
    - diff-so-fancy
    - git-delta
    - grip
    # git-flow-avh
  pacman_packages:
    - git
    - tig
    - hub
    - github-cli
    - diff-so-fancy
    - git-delta
  aur_packages:
    - python-grip
