---
git_config:
  path: shell/git
  links:
    - config
    - attributes
    - aliases
    - config-bemlo
    - config-notes
    - ignore
    - src: gh-config.yml
      dest: "{{ xdg_config_home }}/gh/"
      rename: config.yml
    - src: gh_browse.sh
      dest: "{{ xdg_bin_home }}/"
      rename: gh_browse
    - src: gh_browse_pull.sh
      dest: "{{ xdg_bin_home }}/"
      rename: gh_browse_pull
    - src: branch_status.sh
      dest: "{{ xdg_bin_home }}/"
      rename: branch_status
    - src: list_branch_files.sh
      dest: "{{ xdg_bin_home }}/"
      rename: list_branch_files
    - src: watch_branches.sh
      dest: "{{ xdg_bin_home }}/"
      rename: watch_branches
    - src: fuzzy_branch.sh
      dest: "{{ xdg_bin_home }}/"
      rename: fuzzy_branch
    - src: branch_pruner.sh
      dest: "{{ xdg_bin_home }}/"
      rename: branch_pruner
    - src: auto_branch_pruner.sh
      dest: "{{ xdg_bin_home }}/"
      rename: auto_branch_pruner
    - src: linear_issue_number.sh
      dest: "{{ xdg_bin_home }}/"
      rename: linear_issue_number
  brew_formulas:
    - git
    - tig
    - hub
    - gh
    - diff-so-fancy
    - git-delta
    - grip
    # git-flow-avh
  pacman_packages:
    - git
    - tig
    - hub
    - github-cli
    - diff-so-fancy
    - git-delta
  aur_packages:
    - python-grip
