---
btop_config:
  path: shell/btop
  brew_formulae:
    - btop
  pacman_packages:
    - btop
  links:
    - btop.conf
    - themes
    - src: btop.desktop
      dest: "{{ xdg_applications_dir }}/"
      condition: "{{ is_arch }}"
