---
rofi_config:
  path: wm/rofi
  links:
    - catppuccin-default.rasi
    - catppuccin-macchiato.rasi
    - config.rasi
    - src: cliphist_rofi_img.sh
      dest: "{{ xdg_bin_home }}/"
      rename: cliphist_rofi_img
  pacman_packages:
    - rofi
    - rofi-calc
    - cliphist
    - gawk
