---
yazi_config:
  path: tools/yazi
  links:
    - src: picker
      dest: "{{ xdg_config_home }}/"
      rename: yazi-picker
    - src: capture_picker.sh
      dest: "{{ xdg_bin_home }}/"
      rename: capture_picker
  pacman_packages:
    - yazi
    - ffmpeg  # video previews
