# Catppuccin Mocha K9s Theme
# https://catppuccin.com/palette/mocha

# 🎨 Palette
foreground: &foreground "#cdd6f4"
background: &background default

black: &black "#181825"
blue: &blue "#89b4fa"
green: &green "#a6e3a1"
grey: &grey "#6c7086"
cyan: &cyan "#94e2d5"
purple: &purple "#cba6f7"
red: &red "#f38ba8"
yellow: &yellow "#f9e2af"
peach: &peach "#fab387"
pink: &pink "#f5c2e7"
lavender: &lavender "#b4befe"
sky: &sky "#89dceb"
overlay: &overlay "#585b70"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *purple
    logoColorMsg: *green
    logoColorInfo: *blue
    logoColorWarn: *yellow
    logoColorError: *red

  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *grey
    border:
      command: *blue
      default: *grey

  help:
    fgColor: *foreground
    bgColor: *background
    sectionColor: *lavender
    keyColor: *peach
    numKeyColor: *pink

  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *background
    buttonBgColor: *blue
    buttonFocusFgColor: *black
    buttonFocusBgColor: *yellow
    labelFgColor: *lavender
    fieldFgColor: *cyan

  info:
    fgColor: *blue
    sectionColor: *foreground
    cpuColor: *green
    memColor: *cyan
    k9sRevColor: *peach

  frame:
    border:
      fgColor: *purple
      focusColor: *yellow
    menu:
      fgColor: *foreground
      keyColor: *peach
      numKeyColor: *pink
    crumbs:
      fgColor: *black
      bgColor: *grey
      activeColor: *yellow
    status:
      newColor: *green
      modifyColor: *yellow
      addColor: *cyan
      pendingColor: *blue
      errorColor: *red
      highlightColor: *peach
      killColor: *overlay
      completedColor: *grey
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *pink
      counterColor: *lavender
      filterColor: *grey

  views:
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *black
      cursorBgColor: *pink
      markColor: *yellow
      header:
        fgColor: *blue
        bgColor: *background
        sorterColor: *yellow

    yaml:
      keyColor: *blue
      colonColor: *foreground
      valueColor: *green

    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
        toggleOnColor: *green
        toggleOffColor: *overlay

    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *pink
      cursorTextColor: *black
      graphicColor: *blue

    picker:
      mainColor: *cyan
      focusColor: *yellow
      shortcutColor: *peach

    charts:
      bgColor: *background
      dialBgColor: *overlay
      chartBgColor: *background
      focusFgColor: *foreground
      focusBgColor: *pink
