---
wayland_config:
  path: display/wayland
  pacman_packages:
    - wayland
    - wayland-protocols
    - libinput
    - wl-clipboard
    - xdg-desktop-portal
    # screenshots
    - grim
    - slurp
    # event viewer
    - wev
