---
wayland_config:
  path: display/wayland
  links:
    - src: screen_record.sh
      dest: "{{ xdg_bin_home }}/"
      rename: screen_record
    - src: satty
      dest: "{{ xdg_config_home }}/"
  pacman_packages:
    - wayland
    - wayland-protocols
    - libinput
    - wl-clipboard
    - xdg-desktop-portal
    # screenshots
    - grim
    - slurp
    - satty
    # screen recording
    - wf-recorder
    # event viewer
    - wev
    # Qt Wayland support
    - qt5-wayland
    - qt6-wayland
