---
wayland_config:
  path: display/wayland
  pacman_packages:
    - wayland
    - wayland-protocols
    - libinput
    - wl-clipboard
    - xdg-desktop-portal
    # screenshots
    - grim
    - slurp
    # screen recording
    - wf-recorder
    # event viewer
    - wev
    # Qt Wayland support
    - qt5-wayland
    - qt6-wayland
