---
ai_config:
  path: tools/ai
  brew_formulas:
    - codex
    - gemini-cli
  brew_casks:
    - chatgpt
    - claude
    - claude-code
    - coderabbit
  npm_packages:
    - "@github/copilot"
  links:
    - src: claude_editor.sh
      dest: "{{ xdg_bin_home }}/"
      rename: claude_editor
    - src: claude_persisted_editor.sh
      dest: "{{ xdg_bin_home }}/"
      rename: claude_persisted_editor
    - src: claude_notification.sh
      dest: "{{ xdg_bin_home }}/"
      rename: claude_notification
    - src: settings.json
      dest: "{{ claude_home }}/"
    - src: statusline.sh
      dest: "{{ claude_home }}/"

claude_home: "~/.claude"
