"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$fill\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "yellow"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = '…/'
fish_style_pwd_dir_length = 1
read_only = ' '

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[▢](green)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "bright-black"

[git_commit]
style = "green"

[git_status]
format = "[( $ahead_behind)]($style)( $conflicted)( $modified)( $deleted)( $staged)( $untracked)"
style = "cyan"
conflicted = '[~$count](red)'
modified = '[!$count](yellow)'
untracked = '[?$count](blue)'
staged = '[+$count](green)'
renamed = '[⇄$count](magenta)'
deleted = '[-$count](red)'
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_state]
format = ' [$state( $progress_current/$progress_total)]($style)'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[fill]
symbol = " "

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
