---
zsh_config:
  path: shell/zsh
  brew_formulae:
    # essentials
    - zsh
    - fzf
    - fd
    - bat
    - less
    - ripgrep
    - coreutils
    - watch
    - tree
    - htop
    - openssh
    - unar
    - starship
    # extras
    - jq
    - yq
    - pandoc
    - mdcat
    - entr
    - parallel
    - hyperfine
    - direnv
    - csvlens
    - miller
    - xsv
    - csvkit
    # misc
    - neofetch
    - terminal-notifier
    - eza
    # screensavers
    - cmatrix
    - cbonsai
    - pipes.sh
  pacman_packages:
    - zsh
    - xclip
    - fzf
    - fd
    - bat
    - ripgrep
    - tree
    - jq
    - pandoc
    - neofetch
    - mdcat
    - entr
    - parallel
    - exa
  aur_packages:
    - yq2-bin
  links:
    - src: zshrc
      rename: .zshrc
    - src: zshenv
      rename: .zshenv
    - src: zshenv
      dest: ~/
      rename: .zshenv
    - src: starship.toml
      dest: "{{ xdg_config_home }}/"
    - src: helpers/preview_flag_docs.sh
      dest: "{{ xdg_bin_home }}/"
      rename: preview_flag_docs

zsh_custom_completion_dir: "~/.zsh/completion"
