---
zsh_config:
  path: shell/zsh
  brew_formulas:
    # essentials
    - zsh
    - fzf
    - fd
    - bat
    - less
    - ripgrep
    - coreutils
    - watch
    - tree
    - htop
    # extras
    - jq
    - yq
    - pandoc
    - mdcat
    - entr
    - parallel
    - hyperfine
    - direnv
    # misc
    - neofetch
    - terminal-notifier
    - exa
  pacman_packages:
    - zsh
    - xclip
    - fzf
    - fd
    - bat
    - ripgrep
    - tree
    - jq
    - pandoc
    - neofetch
    - mdcat
    - entr
    - parallel
    - exa
  aur_packages:
    - yq2-bin
  links:
    - src: zshrc
      rename: .zshrc
    - src: zshenv
      rename: .zshenv
    - src: zshenv
      dest: ~/
      rename: .zshenv
    - src: helpers/preview_flag_docs.sh
      dest: "{{ xdg_bin_home }}/"
      rename: preview_flag_docs

zsh_custom_completion_dir: "~/.zsh/completion"
