unsetopt GLOBAL_RCS

# source env file at root of dotfiles repo
# subshell-elimination: may not make a world of difference, but then again...
# source $(cd ${${(%):-%x}:A:h}/../.. && pwd -P)/env
source $HOME/.dotfiles/env

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE="$XDG_CACHE_HOME/zsh"

export BAT_THEME=base16
export BAT_STYLE=plain

# paths
# Remove duplicates from $PATH (produced by refreshing config)
typeset -aU path
path=( $XDG_BIN_HOME $DOTFILES/bin $DOTFILES_DATA/*.topic/bin(N) $path )
# I don't understand this yet, so I'll keep it commented
# fpath=( $ZDOTDIR/functions $XDG_BIN_HOME $fpath )

# envvars
# export SHELL=$(command -v zsh)
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export PAGER=less
export LESS='-R -i -w -M -z-4 -F'
export LESSHISTFILE="$XDG_DATA_HOME/lesshst"
export CLICOLOR=1

export WORDCHARS='*?_-[]~&;!#$%^(){}<>'

if [[ "$(_os)" == "macos" ]]; then
  # Cache output of brew shellenv
  HOMEBREW_ENV_FILE="$HOME/.homebrew"
  if [[ ! -f "$HOMEBREW_ENV_FILE" ]]; then
    brew shellenv > "$HOMEBREW_ENV_FILE"
  fi
  . "$HOMEBREW_ENV_FILE"

  # For using GNU coreutils with default names
  # Specifically needed for readlink -f
  path=( $HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin $path )
  # Override the version of curl bundled with macOS
  path=( $HOMEBREW_PREFIX/opt/curl/bin $path )

  path=( ~/bin $path )
fi

# initialize enabled topics
_load_all env.zsh
