[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "shell --orphan -- echo -n 'file://'$0 | wl-copy -t text/uri-list && ya emit quit"
desc = "Copy file:// URL to clipboard and quit"

[[mgr.prepend_keymap]]
on   = "<C-y>"
run  = "shell --orphan -- wl-copy -t \"$(file -b --mime-type \"$0\")\" < \"$0\" && ya emit quit"
desc = "Copy binary data to clipboard and quit"

[[mgr.prepend_keymap]]
on   = "o"
run  = "open"
desc = "Open file"

[[mgr.prepend_keymap]]
on   = "a"
run  = "shell --orphan -- satty --filename \"$0\" && ya emit quit"
desc = "Annotate with satty"
