[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "shell --orphan -- echo -n 'file://'$0 | wl-copy -t text/uri-list && ya emit quit"
desc = "Copy file:// URL to clipboard and quit"

[[mgr.prepend_keymap]]
on   = "o"
run  = "open"
desc = "Open file"
