source = ~/.config/hypr/catppuccin-macchiato.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    color = $base
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = $text
    font_size = 72
    font_family = Noto Sans
    position = 0, 100
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %B %d')"
    color = $subtext0
    font_size = 24
    font_family = Noto Sans
    position = 0, 20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = $peach
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text =
    position = 0, -80
    halign = center
    valign = center
}

# vim: ft=hyprlang
