$terminal = kitty
$menu = hyprlauncher

$mainMod = SUPER # Sets "Windows" key as main modifier
$hyper = SUPER_SHIFT_CONTROL_ALT

source = ~/.config/hypr/catppuccin-macchiato.conf
source = ~/.config/hypr/conf.d/*
