---
hyprland_config:
  dirname: hypr
  path: wm/hyprland
  links:
    - hyprland.conf
    - hyprpaper.conf
    - hyprlock.conf
    - hypridle.conf
    - catppuccin-macchiato.conf
    - conf.d
    - src: navigate.sh
      dest: "{{ xdg_bin_home }}/"
      rename: navigate
    - src: focus_or_run.sh
      dest: "{{ xdg_bin_home }}/"
      rename: focus_or_run
    - src: launch_on_workspace.sh
      dest: "{{ xdg_bin_home }}/"
      rename: launch_on_workspace
    - src: reload_services.sh
      dest: "{{ xdg_bin_home }}/"
      rename: reload_services
  pacman_packages:
    - hyprland
    - hyprpaper
    - hyprlock
    - hypridle
    - hyprlauncher
    - hyprpolkitagent
    - xdg-desktop-portal-hyprland
  aur_packages:
    - catppuccin-cursors-macchiato
