---
hyprland_config:
  dirname: hypr
  path: wm/hyprland
  links:
    - hyprland.conf
    - hyprpaper.conf
    - hyprlock.conf
    - hypridle.conf
    - hyprtoolkit.conf
    - catppuccin-macchiato.conf
    - commands.yml
    - conf.d
    - src: navigate.sh
      dest: "{{ xdg_bin_home }}/"
      rename: navigate
    - src: focus_or_run.sh
      dest: "{{ xdg_bin_home }}/"
      rename: focus_or_run
    - src: focus_pinned.sh
      dest: "{{ xdg_bin_home }}/"
      rename: focus_pinned
    - src: launch_on_workspace.sh
      dest: "{{ xdg_bin_home }}/"
      rename: launch_on_workspace
    - src: reload_services.sh
      dest: "{{ xdg_bin_home }}/"
      rename: reload_services
    - src: browse_clients.sh
      dest: "{{ xdg_bin_home }}/"
      rename: browse_clients
    - src: special_paste.sh
      dest: "{{ xdg_bin_home }}/"
      rename: special_paste
    - src: send_home.sh
      dest: "{{ xdg_bin_home }}/"
      rename: send_home
    - src: hyprvoice_toggle.sh
      dest: "{{ xdg_bin_home }}/"
      rename: hyprvoice_toggle
    - src: hyprvoice_panel.sh
      dest: "{{ xdg_bin_home }}/"
      rename: hyprvoice_panel
    - src: toggle_espanso.sh
      dest: "{{ xdg_bin_home }}/"
      rename: toggle_espanso
    - src: delete_prev_word.sh
      dest: "{{ xdg_bin_home }}/"
      rename: delete_prev_word
  pacman_packages:
    - hyprland
    - hyprpaper
    - hyprlock
    - hypridle
    - hyprpolkitagent
    - xdg-desktop-portal-hyprland
    - wtype
  aur_packages:
    - catppuccin-cursors-macchiato
    - hyprvoice-bin
    - whisper.cpp
