---
hyprland_config:
  dirname: hypr
  path: wm/hyprland
  links:
    - hyprland.conf
    - hyprpaper.conf
    - conf.d
    - src: navigate.sh
      dest: "{{ xdg_bin_home }}/"
      rename: navigate
    - src: focus_or_run.sh
      dest: "{{ xdg_bin_home }}/"
      rename: focus_or_run
    - src: launch_on_workspace.sh
      dest: "{{ xdg_bin_home }}/"
      rename: launch_on_workspace
  pacman_packages:
    - hyprland
    - hyprpaper
    # - hyprlock
    # - hypridle
    - xdg-desktop-portal-hyprland
    # display manager
    - greetd
    - greetd-tuigreet
  aur_packages:
    - catppuccin-cursors-macchiato
