matches:
  # Git
  - trigger: ;cl
    replace: "chore(lint): "
  - trigger: ;rc
    replace: "refactor(connections): "
  - trigger: ;lb
    label: Insert command to check out a branch name copied from linear
    replace: git checkout -b {{branch_name}}
    vars:
      - name: branch_name
        type: clipboard

  # Browser
  - trigger: ;lh0
    replace: localhost:8000
  - trigger: ;lh1
    replace: localhost:8001
  - trigger: ;lh4
    replace: localhost:4000

  # Web
  - trigger: ;cn
    replace: className="$|$"
