---
kubernetes_config:
  path: dev/kubernetes
  links:
    - src: k9s/skin.yml
      dest: "{{ k9s_config_dir }}/"
      rename: skin.yml
    - src: update_kubectl_token.sh
      dest: "{{ xdg_bin_home }}/"
      rename: update_kubectl_token
    - src: copy_and_update_kubectl_token.sh
      dest: "{{ xdg_bin_home }}/"
      rename: copy_and_update_kubectl_token
  brew_formulas:
    - minikube
    - kubectl
    - kind
    - kubeseal
    - openshift-cli
    - helm
    - kustomize
    - k9s
    - skopeo
  pacman_packages:
    - minikube
    - kubectl
    - kubeseal
    - helm
    - kustomize
    - k9s
    - skopeo
  aur_packages:
    - kind-bin
    - origin-client

k9s_config_dir: "{{ xdg_config_home }}/k9s"
