---
kubernetes_config:
  path: dev/kubernetes
  links:
    - src: k9s/skins
      dest: "{{ k9s_config_dir }}/"
      rename: skins
    - src: update_kubectl_token.sh
      dest: "{{ xdg_bin_home }}/"
      rename: update_kubectl_token
    - src: copy_and_update_kubectl_token.sh
      dest: "{{ xdg_bin_home }}/"
      rename: copy_and_update_kubectl_token
  brew_formulae:
    - minikube
    - kubectl
    - kubelogin
    - kind
    - kubeseal
    - helm
    - kustomize
    - k9s
  pacman_packages:
    - minikube
    - kubectl
    - kubeseal
    - helm
    - kustomize
    - k9s
  aur_packages:
    - kind-bin

k9s_config_dir: "{{ xdg_config_home }}/k9s"
