---
arch_config:
  path: base/arch
  links:
    - src: toggle_display_brightness.sh
      dest: "{{ xdg_bin_home }}/"
      rename: toggle_display_brightness
    - src: spotifyctl.sh
      dest: "{{ xdg_bin_home }}/"
      rename: spotifyctl
    - src: chrome-personal.desktop
      dest: "{{ xdg_applications_dir }}/"
    - src: chrome-work.desktop
      dest: "{{ xdg_applications_dir }}/"
    - src: gpg.conf
      dest: ~/.gnupg/
    - autostart.sh
  pacman_packages:
    # base
    - vim
    - man-db
    - man-pages
    - base-devel
    - xdg-user-dirs
    - archlinux-contrib
    - sound-theme-freedesktop
    - pavucontrol
    - playerctl
    # pacman
    - pacman-contrib
    - rebuild-detector
    # tools
    - ranger
    - unzip
    - gucharmap
    - udiskie
    - ddcutil
    - flameshot
    # apps
    - chromium
    - discord
    - obsidian
  aur_packages:
    # pacman
    - informant
    # apps
    - google-chrome
    - spotify
    - dropbox
    - 1password
    - 1password-cli
    - slack-desktop

aur_builder_user_name: aur_builder
