---
arch_config:
  path: base/arch
  links:
    - src: spotifyctl.sh
      dest: "{{ xdg_bin_home }}/"
      rename: spotifyctl
    - src: chrome_personal.sh
      dest: "{{ xdg_bin_home }}/"
      rename: chrome_personal
    - src: chrome_work.sh
      dest: "{{ xdg_bin_home }}/"
      rename: chrome_work
    - src: gpg.conf
      dest: ~/.gnupg/
    - autostart.sh
  pacman_packages:
    - ranger
    - unzip
    - chromium
    - discord
    - gucharmap
    - base-devel
    - udiskie
  aur_packages:
    - google-chrome
    - spotify
    - dropbox
    - 1password
    - 1password-cli
    - slack-desktop

aur_builder_user_name: aur_builder
