require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    'bash',
    'css',
    'dockerfile',
    'go',
    'graphql',
    'hcl',
    'html',
    'http',
    'java',
    'javascript',
    'jsdoc',
    'json',
    'lua',
    'make',
    -- 'markdown',
    -- 'markdown_inline',
    'python',
    'regex',
    -- 'ruby',
    'rust',
    -- 'scss',
    'toml',
    'tsx',
    'typescript',
    'vim',
    -- 'vue',
    'yaml',
    'prisma',
  },
  highlight = {
    enable = true,
    -- additional_vim_regex_highlighting = { 'markdown' },
  },
  indent = {
    enable = false,
    -- disable = { 'yaml' },
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "gnn",
      node_incremental = ".",
      node_decremental = ",",
      scope_incremental = "grc",
    },
  },
}
